import { COMPANY_IDENTITY } from "./profile";

export type PackInput = {
  reference?: string | null;
  title: string;
  description?: string | null;
  issuer?: string | null;
  province?: string | null;
  category?: string | null;
  closingAt?: string | null;
  estimatedValue?: number | null;
  currency?: string | null;
  fitScore: number;
  scoreBreakdown: Record<string, number | string>;
};

function escapePdf(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapLines(text: string, maxLen = 88): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const next = line ? `${line} ${w}` : w;
    if (next.length > maxLen) {
      if (line) lines.push(line);
      line = w;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/** Minimal hand-rolled PDF — no external deps. */
export function buildCredentialsPackPdf(input: PackInput): Buffer {
  const fmt = (n: number) =>
    new Intl.NumberFormat("en-ZA", {
      style: "currency",
      currency: input.currency ?? "ZAR",
      maximumFractionDigits: 0,
    }).format(n);

  const rawLines = [
    "RED CHERRY INTERACTIVE — CREDENTIALS PACK (DRAFT)",
    "",
    COMPANY_IDENTITY.legalName,
    COMPANY_IDENTITY.location,
    `${COMPANY_IDENTITY.beeLevel} · ${COMPANY_IDENTITY.phone}`,
    "",
    "BRIEF SUMMARY",
    `Reference: ${input.reference ?? "—"}`,
    `Title: ${input.title}`,
    `Issuer: ${input.issuer ?? "—"}`,
    `Province: ${input.province ?? "—"}`,
    `Category: ${input.category ?? "—"}`,
    `Closing: ${input.closingAt ?? "—"}`,
    ...(input.estimatedValue != null ? [`Estimated value: ${fmt(input.estimatedValue)}`] : []),
    "",
    ...(input.description ? [`Description: ${input.description}`, ""] : []),
    "FIT SCORE",
    `Score: ${input.fitScore}/100`,
    "",
    "SCORE BREAKDOWN",
    ...Object.entries(input.scoreBreakdown).map(([k, v]) => `${k}: ${v}`),
    "",
    "Generated by Cherry Ops · Opportunity Ops",
  ];

  const wrapped = rawLines.flatMap((l) => (l === "" ? [""] : wrapLines(l)));

  const streamParts = ["BT", "/F1 11 Tf", "14 TL", "50 750 Td"];
  for (let i = 0; i < wrapped.length; i++) {
    if (i > 0) streamParts.push("T*");
    streamParts.push(`(${escapePdf(wrapped[i] || " ")}) Tj`);
  }
  streamParts.push("ET");
  const stream = streamParts.join("\n");

  const parts = [
    "1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n",
    "2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n",
    "3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources<< /Font<< /F1 5 0 R >> >> >>endobj\n",
    `4 0 obj<< /Length ${Buffer.byteLength(stream, "utf8")} >>stream\n${stream}\nendstream\nendobj\n`,
    "5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const part of parts) {
    offsets.push(pdf.length);
    pdf += part;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${parts.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= parts.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer<< /Size ${parts.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}

export function parseScoreBreakdown(raw: string | null | undefined): Record<string, number | string> {
  if (!raw) return {};
  try {
    return JSON.parse(raw) as Record<string, number | string>;
  } catch {
    return {};
  }
}

export function packFromOpportunity(opp: {
  reference?: string | null;
  title: string;
  description?: string | null;
  issuer?: string | null;
  province?: string | null;
  category?: string | null;
  closing_at?: string | null;
  estimated_value?: number | null;
  currency?: string | null;
  fit_score?: number | null;
  score_breakdown?: string | null;
}): Buffer {
  return buildCredentialsPackPdf({
    reference: opp.reference,
    title: opp.title,
    description: opp.description,
    issuer: opp.issuer,
    province: opp.province,
    category: opp.category,
    closingAt: opp.closing_at,
    estimatedValue: opp.estimated_value,
    currency: opp.currency,
    fitScore: opp.fit_score ?? 0,
    scoreBreakdown: parseScoreBreakdown(opp.score_breakdown),
  });
}
